
[[keyboard.bindings]]
chars = "\u001B\r"
key = "Return"
mods = "Shift"

[general]
import = ["/home/jeremy/.config/alacritty/horizon.toml"]

[font]
size = 10

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
opacity = 0.92

[window.class]
general = "Alacritty"
instance = "Alacritty"

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
